# Generated by Django 5.0.6 on 2024-06-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoilo', '0003_alter_workexperience_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
