# Generated by Django 5.0.6 on 2024-06-26 03:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoilo', '0005_about_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.AddField(
            model_name='contact',
            name='linkedin_link',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='resume_link',
            field=models.URLField(default='https://example.com/resume.pdf'),
            preserve_default=False,
        ),
    ]
